version: '3'
services:
    db:
        image: mysql:5.7
        environment: 
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: mydb
            MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
            volumes:
                — pgdatavol:/var/lib/mysql/data
            ports:
                — 3306:3306
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on: 
            - db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8082:80
        volumes:
            - /sessions
volumes: 
    pgdatavol: